# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c94766351ee8f332459876246ab448817a2c662626c850fb1a54e6b2a4d4f38984d7c3370fd22eb2f9cc21d7797f8bd80488f9fc3d4a8ed011c120d30c3517

test:
  secret_key_base: d3147baf57e2d17fe94b64479aaf039fb693281a77a4c4e1a221dc3867c3b59c9a4c679c23fe2b3f3a4af3b9e0029e18bfcc30b0b02173ae858c7e1c3482bb30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
